import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'models.dart';

class ChecklistExportService {
  /// Export checklist as a text file
  static Future<void> exportAsText({
    required List<PackingSection> sections,
    required String destination,
    required String month,
    String? notes,
  }) async {
    try {
      // Generate the text content
      final content = _generateTextContent(
        sections: sections,
        destination: destination,
        month: month,
        notes: notes,
      );

      // Get temporary directory
      final directory = await getTemporaryDirectory();
      final fileName = 'packing_checklist_${DateTime.now().millisecondsSinceEpoch}.txt';
      final file = File('${directory.path}/$fileName');

      // Write content to file
      await file.writeAsString(content);

      // Share the file
      await Share.shareXFiles(
        [XFile(file.path)],
        subject: 'My Packing Checklist - $destination',
        text: 'Here\'s my packing checklist for $destination',
      );
    } catch (e) {
      throw Exception('Failed to export checklist: $e');
    }
  }

  /// Generate text content for the checklist
  static String _generateTextContent({
    required List<PackingSection> sections,
    required String destination,
    required String month,
    String? notes,
  }) {
    final buffer = StringBuffer();

    // Header
    buffer.writeln('═══════════════════════════════════════════════════');
    buffer.writeln('           PACKING CHECKLIST');
    buffer.writeln('═══════════════════════════════════════════════════');
    buffer.writeln();
    buffer.writeln('Destination: $destination');
    buffer.writeln('Month: ${monthName(int.parse(month))}');
    buffer.writeln('Generated: ${DateTime.now().toString().split('.')[0]}');
    buffer.writeln();

    if (notes != null && notes.isNotEmpty) {
      buffer.writeln('Notes: $notes');
      buffer.writeln();
    }

    // Calculate statistics
    int totalItems = 0;
    int checkedItems = 0;
    for (var section in sections) {
      totalItems += section.items.length;
      checkedItems += section.items.where((item) => item.checked).length;
    }

    buffer.writeln('Progress: $checkedItems / $totalItems items packed');
    buffer.writeln('═══════════════════════════════════════════════════');
    buffer.writeln();

    // Sections and items
    for (var section in sections) {
      buffer.writeln('─────────────────────────────────────────────────');
      buffer.writeln('${section.title.toUpperCase()}');
      buffer.writeln('─────────────────────────────────────────────────');

      for (var item in section.items) {
        final checkbox = item.checked ? '[✓]' : '[ ]';
        final quantity = item.quantity > 1 ? ' (x${item.quantity})' : '';
        buffer.write('  $checkbox ${item.name}$quantity');
        
        if (item.notes != null && item.notes!.isNotEmpty) {
          buffer.write(' - ${item.notes}');
        }
        
        buffer.writeln();
      }
      buffer.writeln();
    }

    // Footer
    buffer.writeln('═══════════════════════════════════════════════════');
    buffer.writeln('          Generated by Raahi AI');
    buffer.writeln('═══════════════════════════════════════════════════');

    return buffer.toString();
  }

  /// Export checklist as a CSV file (alternative format)
  static Future<void> exportAsCSV({
    required List<PackingSection> sections,
    required String destination,
    required String month,
  }) async {
    try {
      // Generate CSV content
      final content = _generateCSVContent(
        sections: sections,
        destination: destination,
        month: month,
      );

      // Get temporary directory
      final directory = await getTemporaryDirectory();
      final fileName = 'packing_checklist_${DateTime.now().millisecondsSinceEpoch}.csv';
      final file = File('${directory.path}/$fileName');

      // Write content to file
      await file.writeAsString(content);

      // Share the file
      await Share.shareXFiles(
        [XFile(file.path)],
        subject: 'My Packing Checklist - $destination',
        text: 'Here\'s my packing checklist for $destination',
      );
    } catch (e) {
      throw Exception('Failed to export checklist: $e');
    }
  }

  /// Generate CSV content
  static String _generateCSVContent({
    required List<PackingSection> sections,
    required String destination,
    required String month,
  }) {
    final buffer = StringBuffer();

    // CSV Header
    buffer.writeln('Category,Item,Quantity,Packed,Notes');

    // Data rows
    for (var section in sections) {
      for (var item in section.items) {
        final packed = item.checked ? 'Yes' : 'No';
        final notes = item.notes?.replaceAll(',', ';') ?? '';
        buffer.writeln('${section.title},${item.name},${item.quantity},$packed,$notes');
      }
    }

    return buffer.toString();
  }

  /// Export checklist as Markdown (for documentation)
  static Future<void> exportAsMarkdown({
    required List<PackingSection> sections,
    required String destination,
    required String month,
    String? notes,
  }) async {
    try {
      // Generate Markdown content
      final content = _generateMarkdownContent(
        sections: sections,
        destination: destination,
        month: month,
        notes: notes,
      );

      // Get temporary directory
      final directory = await getTemporaryDirectory();
      final fileName = 'packing_checklist_${DateTime.now().millisecondsSinceEpoch}.md';
      final file = File('${directory.path}/$fileName');

      // Write content to file
      await file.writeAsString(content);

      // Share the file
      await Share.shareXFiles(
        [XFile(file.path)],
        subject: 'My Packing Checklist - $destination',
        text: 'Here\'s my packing checklist for $destination',
      );
    } catch (e) {
      throw Exception('Failed to export checklist: $e');
    }
  }

  /// Generate Markdown content
  static String _generateMarkdownContent({
    required List<PackingSection> sections,
    required String destination,
    required String month,
    String? notes,
  }) {
    final buffer = StringBuffer();

    // Header
    buffer.writeln('# 🎒 Packing Checklist');
    buffer.writeln();
    buffer.writeln('**Destination:** $destination');
    buffer.writeln('**Month:** ${monthName(int.parse(month))}');
    buffer.writeln('**Generated:** ${DateTime.now().toString().split('.')[0]}');
    buffer.writeln();

    if (notes != null && notes.isNotEmpty) {
      buffer.writeln('> **Notes:** $notes');
      buffer.writeln();
    }

    // Calculate statistics
    int totalItems = 0;
    int checkedItems = 0;
    for (var section in sections) {
      totalItems += section.items.length;
      checkedItems += section.items.where((item) => item.checked).length;
    }

    buffer.writeln('**Progress:** $checkedItems / $totalItems items packed');
    buffer.writeln();
    buffer.writeln('---');
    buffer.writeln();

    // Sections
    for (var section in sections) {
      buffer.writeln('## ${section.title}');
      buffer.writeln();

      for (var item in section.items) {
        final checkbox = item.checked ? 'x' : ' ';
        final quantity = item.quantity > 1 ? ' **(x${item.quantity})**' : '';
        buffer.write('- [$checkbox] ${item.name}$quantity');
        
        if (item.notes != null && item.notes!.isNotEmpty) {
          buffer.write(' - *${item.notes}*');
        }
        
        buffer.writeln();
      }
      buffer.writeln();
    }

    buffer.writeln('---');
    buffer.writeln('*Generated by Raahi AI*');

    return buffer.toString();
  }
}